version: '3'
services:
  react-app:  #nazwa serwisu (dowolna)
    build:  # build, bo z dockerfile'a
      context: . #ściezka do dockerfile'a
      dockerfile: Dockerfile.dev #nazwa dockerfile'a
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]